global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'category', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'null-receiver'

receivers:
  - name: 'null-receiver'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
