global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - "/etc/prometheus/alerts.yml"


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'weather-producer'
    static_configs:
      - targets: ['producer:8000']

  - job_name: 'weather-consumer'
    static_configs:
      - targets: ['consumer:8001']

  - job_name: 'weather-alert-service'
    static_configs:
      - targets: ['alert-service:8002']

  - job_name: 'weather-api-service'
    static_configs:
      - targets: ['api-service:8003']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
